export const permissionCodes = [
  "company.read",
  "company.manage",
  "drivers.read",
  "drivers.manage",
  "vehicles.read",
  "vehicles.manage",
  "vehicles.odometer.submit",
  "vehicles.odometer.review",
  "inspections.submit",
  "inspections.read",
  "inspections.review",
  "inspections.manage",
  "inspections.configure",
  "defects.read",
  "defects.manage",
  "tasks.read",
  "tasks.manage",
  "maintenance.read",
  "maintenance.manage",
  "documents.read",
  "documents.file.read",
  "documents.manage",
  "documents.review",
  "compliance.read",
  "compliance.manage",
  "reports.read",
  "integrations.read",
  "integrations.manage",
] as const;

export type PermissionCode = (typeof permissionCodes)[number];

export const roleCodes = ["OWNER", "ADMIN", "MANAGER", "SUPERVISOR", "DRIVER"] as const;
export type RoleCode = (typeof roleCodes)[number];

const allPermissions = [...permissionCodes];

export const rolePermissionMatrix: Record<RoleCode, readonly PermissionCode[]> = {
  OWNER: allPermissions,
  ADMIN: allPermissions,
  MANAGER: [
    "company.read",
    "drivers.read",
    "drivers.manage",
    "vehicles.read",
    "vehicles.manage",
    "vehicles.odometer.submit",
    "vehicles.odometer.review",
    "inspections.submit",
    "inspections.read",
    "inspections.review",
    "inspections.manage",
    "inspections.configure",
    "defects.read",
    "defects.manage",
    "tasks.read",
    "tasks.manage",
    "maintenance.read",
    "maintenance.manage",
    "documents.read",
    "documents.file.read",
    "documents.manage",
    "documents.review",
    "compliance.read",
    "compliance.manage",
    "reports.read",
  ],
  SUPERVISOR: [
    "company.read",
    "drivers.read",
    "vehicles.read",
    "vehicles.odometer.submit",
    "vehicles.odometer.review",
    "inspections.submit",
    "inspections.read",
    "inspections.review",
    "inspections.manage",
    "inspections.configure",
    "defects.read",
    "defects.manage",
    "tasks.read",
    "tasks.manage",
    "maintenance.read",
    "documents.read",
    "documents.file.read",
    "documents.manage",
    "documents.review",
    "compliance.read",
  ],
  DRIVER: [
    "drivers.read",
    "vehicles.read",
    "vehicles.odometer.submit",
    "inspections.submit",
    "inspections.read",
    "documents.read",
    "documents.file.read",
    "compliance.read",
  ],
};

export function isPermissionCode(value: string): value is PermissionCode {
  return (permissionCodes as readonly string[]).includes(value);
}
